### ISSUE TITLE
Add getYsparse function

### ISSUE THREAD

**Issue by kdheepak** [NREL/OpenDSSDirect.py#5]
See existing implementation [here](https://github.com/tshort/OpenDSSDirect.jl/blob/734bba53d9e0fd2c34daed2b7743a278b992f428/src/core.jl#L282-L298) for reference.

**Comment by PMeira** [comment]
I think we can close this since it was added here: https://github.com/NREL/OpenDSSDirect.py/blob/40b13b3f217c3536dfc79ecabea42dd467dd74a4/opendssdirect/YMatrix.py#L5

I didn't make it return a sparse matrix object as that would introduce a dependency on another module.
